// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.product.domain;

import com.product.domain.CheckProduct;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CheckProduct_Roo_Configurable {
    
    declare @type: CheckProduct: @Configurable;
    
}
